In [0]:
import numpy as np
import gym
import random

In [0]:
env=gym.make("FrozenLake-v0")

In [0]:
action_size=env.action_space.n
state_size=env.observation_space.n
qtable=np.zeros((state_size,action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
total_episodes=20000
learning_rate=0.8
max_steps=99
gamma=0.95
epsilon=1.0
max_epsilon=1.0
min_epsilon=0.01
decay_rate=0.005

In [0]:
rewards=[]
for episode in range(total_episodes):
  state=env.reset()
  step=0
  done=False
  total_rewards=0

  for step in range(max_steps):
    exp_exp_tradeoff=random.uniform(0,1)
    if exp_exp_tradeoff>epsilon:
      action=np.argmax(qtable[state,:])
    else:
      action=env.action_space.sample()
    new_state,reward,done,info=env.step(action)
    qtable[state,action]=qtable[state,action]+learning_rate*(reward+gamma * np.max(qtable[new_state,:])-qtable[state,action])
    total_rewards+=reward
    state=new_state

    if done==True:
      break
  epsilon=min_epsilon+(max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)
  rewards.append(total_rewards)


print("Score over time: "+str(sum(rewards)/total_episodes))



Score over time: 0.4925


In [0]:
print(qtable)

[[5.76928621e-02 3.04508635e-02 2.72886413e-01 5.12451157e-02]
 [5.04038644e-03 1.65339965e-02 5.21268743e-03 1.85622604e-01]
 [3.54391450e-01 1.04162993e-02 1.06882183e-02 1.07473223e-02]
 [2.15936717e-03 4.80443084e-03 2.63201586e-03 1.03296578e-02]
 [1.28777909e-01 5.98695119e-03 4.45904492e-02 8.89805854e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.54804135e-02 8.72269041e-09 1.72413733e-05 1.40915531e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.70313422e-02 1.09889854e-02 1.11117703e-02 2.84200485e-01]
 [1.03510393e-01 2.00381739e-01 1.59217463e-01 7.88993761e-02]
 [3.85802414e-01 5.73083621e-05 2.90156109e-03 2.04339368e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.19822717e-01 2.18992218e-02 4.35809100e-01 1.06214872e-01]
 [1.64293449e-01 7.32291301e-01 3.20924970e-01 1.66531580e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [0]:
env.reset()

for episode in range(10):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
    
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
          
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 6
****************************************************
EPISODE  1
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 45
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 11
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 56
****************************************************
EPISODE  4
****************************************************
EPISODE  5
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 41
****************************************************
EPISODE  6
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 78
****************************************************
EPISODE  7
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 19
****************************************************
EPISODE  8
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 25
*****************************************